name: Timer Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: "pnpm"

      - name: Install Packages
        run: pnpm i

      - name: Testing the code
        run: pnpm test

      - name: Build
        run: pnpm run build
